import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("data/cleaned_Dataset for Data Analytics.csv")

print(df.head())

product_revenue = df.groupby('Product')['TotalPrice'].sum()

product_revenue.sort_values(ascending=False).plot(
    kind='bar',
    figsize=(10,5)
)

plt.title("Revenue Generated by Product")
plt.xlabel("Product")
plt.ylabel("Revenue")

plt.tight_layout()

plt.savefig("charts/revenue_by_product.png")

plt.show()

df['PaymentMethod'].value_counts().plot(
    kind='bar',
    figsize=(8,5)
)

plt.title("Payment Method Usage")
plt.xlabel("Payment Method")
plt.ylabel("Orders")

plt.tight_layout()

plt.savefig("charts/payment_method_usage.png")

plt.show()

df['OrderStatus'].value_counts().plot(
    kind='pie',
    autopct='%1.1f%%'
)

plt.title("Order Status Distribution")

plt.ylabel("")

plt.savefig("charts/order_status_distribution.png")

plt.show()

df['ReferralSource'].value_counts().plot(
    kind='bar'
)

plt.title("Customer Acquisition Sources")
plt.xlabel("Referral Source")
plt.ylabel("Customers")

plt.tight_layout()

plt.savefig("charts/referral_sources.png")

plt.show()

plt.hist(df['TotalPrice'])

plt.title("Revenue Distribution")
plt.xlabel("Order Value")
plt.ylabel("Frequency")

plt.tight_layout()

plt.savefig("charts/revenue_distribution.png")

plt.show()

top_products = (
    df.groupby('Product')['TotalPrice']
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

top_products.plot(kind='bar')

plt.title("Top 10 Revenue Generating Products")

plt.tight_layout()

plt.savefig("charts/top10_products.png")

plt.show()